version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Build with Maven
          command: mvn clean install
      - run:
          name: Run tests and collect coverage
          command: mvn -B test
      - codecov/upload

workflows:
  version: 2.1
  build-projet:
    jobs:
      - build: