version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Build with Maven
          command: mvn clean install
      - run:
          name: Run Checkstyle
          command: mvn checkstyle:check
      - run:
          name: Run tests and collect coverage
          command: mvn -B test
      - run:
        name: Build docs
        command: mvn -B javadoc:javadoc
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.DOC_TOKEN }}
          publish_dir: ./target/reports/apidocs
      - codecov/upload

workflow:
  version: 2.1
  build-test:
    jobs:
      - build: