version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Build with Maven
          command: mvn clean install

workflows:
  version: 2
  upload-to-circle-ci:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - codecov/upload:
            requires:
                - build
            filters:
                branches:
                only: master