version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Build with Maven
          command: mvn clean install
orbs:
    codecov: codecov/codecov@4.0.1
workflows:
  version: 2
  upload-to-circle-ci:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - checkout
      - codecov/upload
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: master