version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Build with Maven
          command: mvn clean install
      - run:
          name: Run Checkstyle
          command: mvn checkstyle:check
      - run:
          name: Run tests and collect coverage
          command: mvn -B test
      - run:
          name: Build docs
          command: mvn -B javadoc:javadoc
      - run:
          name: Deploy to GitHub Pages
          command: |
            git config --global user.email "simon.diaz@alumni.univ-avignon.fr"
            git config --global user.name "simondiaz-uapv"
            git clone https://$GITHUB_TOKEN@github.com/simondiaz-uapv/ceri-m1-techniques-de-test.git gh-pages
            cd gh-pages
            git checkout -b gh-pages || git checkout gh-pages
            cp -R ../target/reports/apidocs/* .
            git add .
            git commit -m "Update Javadocs"
            git push origin gh-pages
      - codecov/upload

workflows:
  version: 2
  build-test:
    jobs:
      - build